---
name: Pre-requisites
description: |
  Setup Pre-requisites

inputs:
  token:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ inputs.token }}
        persist-credentials: true

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        run_install: false

    - name: Use node@22
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 22.18.0
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        pnpm install-deps
      shell: bash
