# Public npm version check workflow
# =================================

name: Check Version Sync

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'

permissions:
  contents: read

jobs:
  check-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Check if app creds exist (base repo only)
        id: has-app
        run: |
          present=true
          if [ "${{ github.event.pull_request.head.repo.fork || false }}" = "true" ]; then present=false; fi
          if [ -z "${{ vars.GH_APP_ID }}" ] || [ -z "${{ secrets.GH_APP_PRIVATE_KEY }}" ]; then present=false; fi
          echo "present=$present" >> "$GITHUB_OUTPUT"

      - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: gh-app-token
        if: steps.has-app.outputs.present == 'true'
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Select token
        id: auth
        run: |
          if [ "${{ steps.has-app.outputs.present }}" = "true" ]; then
            echo "token=${{ steps.gh-app-token.outputs.token }}" >> "$GITHUB_OUTPUT"
          else
            echo "token=${{ github.token }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare pre-requisites
        uses: ./.github/actions/prepare
        with:
          token: ${{ steps.auth.outputs.token }}

      - name: Configure npm authentication for npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Update export versions
        run: pnpm run update-export-versions

      - name: Check for changes
        run: |
          if ! git diff --exit-code packages/builder/src/export/versions.ts; then
            echo "❌ Error: versions.ts is out of sync with package.json versions"
            echo "Please run 'pnpm run update-export-versions' and commit the changes"
            exit 1
          fi
          echo "✅ versions.ts is synchronized with package.json versions"
