# Public npm CI workflow
# ======================

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: gh-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.5.4

      - name: Prepare pre-requisites
        uses: ./.github/actions/prepare
        with:
          token: ${{ steps.gh-app-token.outputs.token }}

      - name: Configure npm authentication for npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm -r build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'

      - name: Test ES module imports
        run: |
          cat > test-es-modules.mjs << 'EOF'
          import { logger } from './packages/utils/dist/index.js';
          import { isEvmNetworkConfig } from './packages/types/dist/index.js';
          if (typeof logger === 'object' && typeof isEvmNetworkConfig === 'function') {
            console.log('✅ ES modules working correctly');
            process.exit(0);
          } else {
            console.error('❌ ES module imports failed');
            process.exit(1);
          }
          EOF
          node test-es-modules.mjs
          rm test-es-modules.mjs

      - name: Test
        run: pnpm test
        # It's okay if no tests exist yet
        continue-on-error: true
