# Manual deprecation of legacy npm packages using repo NPM_TOKEN

name: Deprecate Legacy Packages

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in DRY_RUN mode (prints actions only)"
        required: false
        default: "true"
        type: choice
        options: ["true", "false"]

permissions:
  contents: read

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.2.0
        with:
          node-version: '22.x'

      - name: Deprecate legacy packages (DRY_RUN=${{ inputs.dry_run }})
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          bash scripts/rename/update-legacy-packages.sh


