# PRIVATE REGISTRY RELEASE WORKFLOW
# ==================================
# This workflow handles both CI and publishing for the private registry.
# All @openzeppelin packages (including dependencies) are resolved from the private registry
# due to organization-level scoping in .npmrc.
#
# AUTHENTICATION:
# The workflow uses the NPM_TOKEN secret for authentication to GitHub Package Registry.
# This should be a Personal Access Token (PAT) with `read:packages` and `write:packages`
# permissions to avoid GitHub Package Registry permission limitations.
#
# TRANSITION TO PUBLIC RELEASE:
# When ready to publish publicly, update this workflow to:
# 1. Update the .npmrc authentication to use NPM_TOKEN for npm registry
# 2. Update the Changesets publish command to target npm registry
# 3. Ensure .npmrc is updated (see .npmrc comments)
# 4. All package names and imports will remain the same

name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write # ✅ Includes both read and write permissions
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # This is needed for changesets to calculate version based on commit history
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.10.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Configure npm authentication for private registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Verify dependencies
        run: pnpm audit
        continue-on-error: true

      - name: Build all packages
        run: pnpm build

      - name: Test all packages
        run: pnpm test

      - name: Create .npmrc for publishing
        run: |
          cat << EOF > "$HOME/.npmrc"
          @openzeppelin:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
          always-auth=true
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Debug step to verify authentication
      - name: Verify npm authentication
        run: |
          echo "Testing npm authentication..."
          npm whoami --registry https://npm.pkg.github.com || echo "Authentication test failed"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # CURRENT: Publishing to GitHub private registry using Changesets
      # FUTURE: When going public, this will automatically switch to npm registry
      - name: Create Release Pull Request or Publish to GitHub
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0 # Disable husky hooks for automated changeset commits
